---
apiVersion: v1
kind: Pod
metadata: 
  name: "web-and-db-pod"
spec:
  containers:
    - name: nginx-c
      image: docker.io/nginx:stable-alpine-perl
      ports:
        - name: http-web
          containerPort: 80
          protocol: TCP
    - name: postgres-c
      image: docker.io/postgres:14.20-trixie
      ports:
        - name: db-port
          containerPort: 5432
          protocol: TCP
      env: 
        - name: POSTGRES_PASSWORD
          value: "secret123"
